---
server:
  port: "${SERVER_PORT}"
spring:
  data:
    cassandra:
      keyspace-name: "${CASSANDRA_KEYSPACE}"
      local-datacenter: "${CASSANDRA_DATACENTER}"
      password: "${CASSANDRA_PASSWORD}"
      schema-action: "${CASSANDRA_SCHEMA}"
      username: "${CASSANDRA_USERNAME}"
