---
server:
  port: "${SERVER_PORT}"
spring:
  h2:
    console:
      enabled: "${H2_ENABLE_CONSOLE}"
      path: "${H2_PATH}"
  datasource:
    url: "${H2_URL}"
    username: "${H2_USERNAME}"
    password:
    driverClassName: "${H2_DRIVER}"
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: "${FB_CLIENTID}"
            clientSecret: "${FB_CLIENTSECRET}"
            scope: email, public_profile
