version: "3.8"

services:
  db:
    image: mysql:latest # use latest version of mysql
    container_name: mysql # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: tacocloud # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes: # add persistent data even if container is removed.
  my-db:
